server:
  port: 8883  # Change this per service

spring:
  application:
    name: order-service  # e.g., product-service
  config:
    import: optional:configserver:http://localhost:8884  # Optional: if using Spring Cloud Config

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 2s
    