server:
  port: 8884  # Change this per service

spring:
  application:
    name: product-service  # e.g., product-service
  config:
    import: optional:configserver:http://localhost:8884  # Optional: if using Spring Cloud Config

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
  instance:
    prefer-ip-address: true
    hostname: localhost

