server:
  port: 8885

spring:
  application:
    name: product-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://amazon-server:8761/eureka/
  instance:
    prefer-ip-address: true    
    instance-id: ${spring.application.name}:${server.port}
